version: "3"

services:
  app:
    build: .
    # entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    container_name: app
    restart: always
    tty: true
    # volumes:
    #   - .:/var/www
    networks:
      - app-network
    # environment:
    #   - DB_HOST=db
    #   - DB_PORT=3306
    #   - DB_DATABASE=laravel
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=root
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    # entrypoint: dockerize -template ./nginx.conf:/etc/nginx/conf.d/nginx.conf -wait tcp://app:9000 -timeout 30s nginx -g 'daemon off;'
    container_name: nginx
    restart: always
    tty: true
    environment:
      - APP_PHP_FPM_SERVER=app
      - APP_PHP_FPM_PORT=9000
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    tty: true
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
