version: "2.3"

services:
  app:
    build: .
    container_name: app
    restart: always
    tty: true
    volumes:
      - .:/var/www
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mysql -uroot --database=laravel --password=root --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B',
        ]
      interval: 10s
      timeout: 10s
      retries: 4
    networks:
      - app-network

  redis:
    image: redis:alpine
    restart: always
    tty: true
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
